management:
  endpoints:
    enabled-by-default: false
spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_DB_USERNAME:}:${MONGO_DB_PASSWORD:}@gamegeekscluster.4pfxjyv.mongodb.net/gamegeeks-db?retryWrites=true&w=majority
      auto-index-creation: true
  jackson:
    deserialization:
      fail-on-ignored-properties: true
      fail-on-unknown-properties: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_JWT_ISSUER_URI:http://localhost:8080/realms/game-geeks}
          jwk-set-uri: ${OAUTH2_JWT_SET_URI:http://localhost:8080/realms/game-geeks/protocol/openid-connect/certs}
springdoc:
  api-docs:
    enabled: true
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    use-root-path: true
  cache:
    disabled: true
  oAuthFlow:
    authorization-url: http://localhost:8080/realms/game-geeks
    token-url: http://localhost:8080/realms/game-geeks/protocol/openid-connect/token
logging:
  level:
    root: debug
